

server:
  port: 8089
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${eureka.service.url:http://localhost:8080/eureka}

management:
  security:
    enabled: false
    

  
logging:
  config: classpath:log/logback.xml

    